### ISSUE TITLE
Adding images to fellows that don't currently have them

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/django-app#476]

**Comment by kallewesterling** [comment]
@gofilipa I believe there's a bunch of them available in the directory in the DHRI website so that may be a good place to start looking.

Perhaps then, you can just add the images to the repository, and then, following the instruction for [adding the new users](http://docs.dhinstitutes.org/settings/add-new-user/), edit the information for the missing users (they should already be in the `backend/setup/users.yml` file).

If you need help, just let me know! I'll get cracking on the other things. So much to do, so few hours to do it :/

**Comment by kallewesterling** [comment]
Many images here: https://www.dhinstitutes.org/assets/images/people/

**Comment by gofilipa** [comment]
Just added missing images and image paths for fellows (Olivia, Javi, Jojo & Patrick Smyth). Closing out.
