### ISSUE TITLE
Add Connor's profile photo to backup/setup/profile-pictures 

### ISSUE THREAD

**Issue by connor-french** [DHRI-Curriculum/django-app#502]
@gofilipa Can you add the photo I sent you on slack and name it connor-french.jpg? 
Also, my profile wasn't on the website. I created another pull request because I think this was due to me putting my profile info in the wrong section on the yaml.

**Comment by kallewesterling** [comment]
I can confirm that that's correct :)

**Comment by gofilipa** [comment]
done & done!
